### ISSUE TITLE
not found models/model.zh.seed-1

### ISSUE THREAD

**Issue by canghaiyunfan** [Jacob-Zhou/gecdi#3]
感谢作者开源代码，但运行pred_zh.sh 过程中遇到了问题

RuntimeError: File models/model.zh.seed-1 unavailable. Please try other sources.

想请教下脚本中用到的文件 去哪下载，例如
gec_path:=models/model.zh.seed-1
lm_path:=uer/gpt2-chinese-cluecorpussmall
ged_path:=models/ged_model.zh.seed-1
mucgec.dev.collapsed

**Comment by Jacob-Zhou** [comment]
您好，GEC 和 GED 文件可以参考 [Download Trained Models](https://github.com/Jacob-Zhou/gecdi#download-trained-models) 章节下载，其中 GEC 和 GED 文件的仓库名 HQZhou/bart-large-chinese-gec 和 HQZhou/bart-large-chinese-ged, 下载完后请参考 [Run](https://github.com/Jacob-Zhou/gecdi#run) 设置路径。

数据集文件可以到 [MuCGEC](https://github.com/HillZhang1999/MuCGEC) 中下载，然后参考 [Setup](https://github.com/Jacob-Zhou/gecdi#setup) 修改格式。

**Comment by canghaiyunfan** [comment]
@Jacob-Zhou 按照要求下载文件后仍报错

config:    configs/bart.ini
path:      /tmp/tmp.KdmvoLL3Sr
suffix:    
gec_path:  models/gecdi/bart-large-gec/model
lm_path:   uer/gpt2-chinese-cluecorpussmall
lm_alpha:  0.0
lm_beta:   0
ged_path:  models/gecdi/bart-large-ged/model
ged_alpha: 0.0
ged_beta:  0
devices:   0
batch:     1000
beam:      12
dataset:   mucgec.dev
data:      data/cgec/mucgec.dev.collapsed
gold:      data/cgec/mucgec.dev.m2
pred:      models/gecdi/bart-large-gec/pred/mucgec.dev/baseline/mucgec.dev.beam-12.pred
Traceback (most recent call last):
  File "gecdi/scripts/predict_utils/split_discourse.py", line 25, in <module>
    tokenize_func = Seq2SeqParser.load(args.path).SRC.tokenize
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "gecdi/supar/parser.py", line 495, in load
    model.load_state_dict(state['state_dict'], False)
  File "/miniconda3/envs/bert/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Seq2SeqModel:
        size mismatch for model.shared.weight: copying a param with shape torch.Size([50265, 1024]) from checkpoint, the shape in current model is torch.Size([50264, 1024]).
        size mismatch for model.encoder.embed_tokens.weight: copying a param with shape torch.Size([50265, 1024]) from checkpoint, the shape in current model is torch.Size([50264, 1024]).
        size mismatch for model.decoder.embed_tokens.weight: copying a param with shape torch.Size([50265, 1024]) from checkpoint, the shape in current model is torch.Size([50264, 1024]).
        size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([50265, 1024]) from checkpoint, the shape in current model is torch.Size([50264, 1024]).
        size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([50265, 1024]) from checkpoint, the shape in current model is torch.Size([50264, 1024]).
        size mismatch for classifier.weight: copying a param with shape torch.Size([50265, 1024]) from checkpoint, the shape in current model is torch.Size([50264, 1024]).

**Comment by Jacob-Zhou** [comment]
您好我这边尝试复现一下这个问题，可能需要点时间。
